version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: bijoukart-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME:-admin}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD:-changeme}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE:-bijoukart}
    volumes:
      - mongodb_data:/data/db
    # Remove external port exposure for security and resource saving
    networks:
      - bijoukart-network
    # Memory limit for free tier
    deploy:
      resources:
        limits:
          memory: 256M

  bijoukart-app:
    build: .
    container_name: bijoukart-app
    restart: unless-stopped
    environment:
      NODE_ENV: ${NODE_ENV:-production}
      PORT: ${PORT:-5000}
      MONGODB_URI: mongodb://${MONGO_USERNAME:-admin}:${MONGO_PASSWORD:-changeme}@mongodb:27017/${MONGO_DATABASE:-bijoukart}?authSource=admin
      JWT_SECRET: ${JWT_SECRET:-change_this_secret}
      STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY}
      STRIPE_PUBLISHABLE_KEY: ${STRIPE_PUBLISHABLE_KEY}
      EMAIL_HOST: ${EMAIL_HOST:-smtp.gmail.com}
      EMAIL_PORT: ${EMAIL_PORT:-587}
      EMAIL_USER: ${EMAIL_USER}
      EMAIL_PASS: ${EMAIL_PASS}
    volumes:
      - ./backend/uploads:/app/uploads
    ports:
      - "80:5000"
    depends_on:
      - mongodb
    networks:
      - bijoukart-network
    # Memory limit for free tier
    deploy:
      resources:
        limits:
          memory: 512M

volumes:
  mongodb_data:

networks:
  bijoukart-network:
    driver: bridge